### ISSUE TITLE
run-all-tests clobbers fiveam:run-all-tests

### ISSUE THREAD

**Issue by quicklisp** [TeMPOraL/cl-sqlite#7]
sqlite-tests.lisp defines a function named run-all-tests, but that symbol is coming from fiveam. The next version of fiveam will signal an error on this redefinition.

**Comment by quicklisp** [comment]
Any update on this?

**Comment by dmitryvk** [comment]
Thanks for reminding. I'll try to fix this before the end of this week.
(But I'm not interested in long-term maintenance - I'd be glad if someone would take over this project).

**Comment by Harleqin** [comment]
I could do that.  Please contact me if you think that I could fit.

**Comment by Shinmera** [comment]
I would also offer to take on the task of maintaining this. I have interest in keeping it alive as well as add some fixes and feature inclusions for the use with Radiance.

**Comment by Harleqin** [comment]
Anything new?  I'm OK with any decision.

**Comment by TeMPOraL** [comment]
Hi there,

I took over maintaining cl-sqlite. I'll fix this issue shortly.
